### ISSUE TITLE
Event templates tracking issue

### ISSUE THREAD

**Issue by ZoopOTheGoop** [ZoopOTheGoop/pond-slime#27]
Add some basic event templates - since we control the code we don't need to do what Sesh does unless during the course of implementation or usage we decide it's necessary.

There should be a few basic templates:

- [ ] Open event (yes/no/interested) #28
- [ ] Ticketed event (interested/confirmed) #31
- [ ] Closed event (confirmed/interested/waitlist) #32
